package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
	"text/template"
)

const tpl = `// Code generated by obsgen. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"
	{{- if .NeedsContext}}
	"context"
	{{- end}}
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	{{- range .Imports}}
	{{.}}
	{{- end}}
)

func (r *{{.Type}}) Observe() any {
	return newObserve{{capitalize .Type}}(r)
}

type observe{{capitalize .Type}} struct {
	*{{.Type}}
	label string
}

func newObserve{{capitalize .Type}}(base *{{.Type}}) *observe{{capitalize .Type}} {
	o := &observe{{capitalize .Type}}{ {{.Type}}: base }
	if l, ok := any(base).(interface{ Label() string }); ok {
		o.label = l.Label()
	}
	return o
}

{{if .HasDeps}}
func (o *observe{{capitalize .Type}}) Deps() []any {
	return o.{{.Type}}.Deps()
}
{{end}}
{{if .HasInject}}
func (o *observe{{capitalize .Type}}) Inject(args []any) {
	o.{{.Type}}.Inject(args)
}
{{end}}
{{if .HasLabel}}
func (o *observe{{capitalize .Type}}) Label() string {
	return o.{{.Type}}.Label()
}
{{end}}

{{range .Methods}}
func (o *observe{{capitalize $.Type}}) {{.Name}}({{.Args}}) {{.Results}} {
{{- if .HasCtx}}
	ctx, span := otel.Tracer("obs").Start(ctx, o.label+"."+"{{.Name}}")
	defer span.End()
{{- end}}
{{- if .HasResults}}
{{- if .HasErr}}
	{{.RetVars}} := o.{{$.Type}}.{{.Name}}({{.CallVars}})
	if err != nil {
{{- if .HasCtx}}
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
{{- end}}
		return {{if .HasResultsBeforeErr}}{{.RetValuesBeforeErr}}, {{end}}fmt.Errorf("[%s] {{.Name}}: %w", o.label, err)
	}
	return {{.RetVars}}
{{- else}}
	return o.{{$.Type}}.{{.Name}}({{.CallVars}})
{{- end}}
{{- else}}
	o.{{$.Type}}.{{.Name}}({{.CallVars}})
{{- end}}
}

{{end}}
`

type Method struct {
	Name                string
	Args                string
	Results             string
	CallVars            string
	RetVars             string
	HasErr              bool
	HasCtx              bool
	HasResults          bool
	HasResultsBeforeErr bool
	RetValuesBeforeErr  string
}

func main() {
	typeName := flag.String("type", "", "struct name to instrument")
	flag.Parse()

	if *typeName == "" {
		log.Fatal("type flag is required")
	}

	fset := token.NewFileSet()
	entries, err := os.ReadDir(".")
	if err != nil {
		log.Fatal(err)
	}

	var pkgName string
	var methods []Method
	var hasDeps, hasInject, hasLabel bool
	importsMap := make(map[string]string)
	skipMethods := map[string]bool{
		"Deps": true, "Inject": true, "NewResource": true,
		"BuildConfig": true, "Observe": true, "Label": true,
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") ||
			strings.HasSuffix(entry.Name(), "_test.go") ||
			strings.HasSuffix(entry.Name(), "_obs_gen.go") {
			continue
		}

		file, err := parser.ParseFile(fset, entry.Name(), nil, parser.ParseComments)
		if err != nil {
			continue
		}

		pkgName = file.Name.Name
		for _, imp := range file.Imports {
			p := imp.Path.Value
			if p != `"fmt"` && p != `"context"` {
				name := ""
				if imp.Name != nil {
					name = imp.Name.String() + " "
				}
				importsMap[p] = name + p
			}
		}

		ast.Inspect(file, func(n ast.Node) bool {
			fn, ok := n.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || !fn.Name.IsExported() {
				return true
			}

			for _, field := range fn.Recv.List {
				var id *ast.Ident
				switch t := field.Type.(type) {
				case *ast.StarExpr:
					if idx, ok := t.X.(*ast.Ident); ok {
						id = idx
					}
				case *ast.Ident:
					id = t
				}

				if id != nil && id.Name == *typeName {
					switch fn.Name.Name {
					case "Deps":
						hasDeps = true
						continue
					case "Inject":
						hasInject = true
						continue
					case "Label":
						hasLabel = true
						continue
					}
					if skipMethods[fn.Name.Name] {
						continue
					}
					methods = append(methods, analyze(fn))
				}
			}
			return true
		})
	}

	var imports []string
	for _, v := range importsUsedByMethods(methods, importsMap) {
		imports = append(imports, v)
	}

	needsContext := false
	for _, m := range methods {
		if m.HasCtx {
			needsContext = true
			break
		}
	}

	funcMap := template.FuncMap{
		"capitalize": func(s string) string {
			if len(s) == 0 {
				return ""
			}
			return strings.ToUpper(s[:1]) + s[1:]
		},
		"lower": strings.ToLower,
	}

	t := template.Must(template.New("gen").Funcs(funcMap).Parse(tpl))
	var buf bytes.Buffer
	err = t.Execute(&buf, struct {
		Package      string
		Type         string
		Methods      []Method
		Imports      []string
		NeedsContext bool
		HasDeps      bool
		HasInject    bool
		HasLabel     bool
	}{pkgName, *typeName, methods, imports, needsContext, hasDeps, hasInject, hasLabel})
	if err != nil {
		log.Fatal("template execution error:", err)
	}

	clean, err := format.Source(buf.Bytes())
	if err != nil {
		os.WriteFile(strings.ToLower(*typeName)+"_obs_gen.go", buf.Bytes(), 0644)
		log.Fatal("format error (debug file saved):", err)
	}
	os.WriteFile(strings.ToLower(*typeName)+"_obs_gen.go", clean, 0644)
}

func analyze(f *ast.FuncDecl) Method {
	m := Method{Name: f.Name.Name}
	var args, cvars, rvars, resTypes []string

	if f.Type.Params != nil {
		for _, field := range f.Type.Params.List {
			tStr := getExprString(field.Type)
			isVariadic := strings.HasPrefix(tStr, "...")

			for _, name := range field.Names {
				args = append(args, name.Name+" "+tStr)
				if isVariadic {
					cvars = append(cvars, name.Name+"...")
				} else {
					cvars = append(cvars, name.Name)
				}

				if tStr == "context.Context" || tStr == "ctx.Context" {
					m.HasCtx = true
				}
			}
		}
	}
	m.Args, m.CallVars = strings.Join(args, ", "), strings.Join(cvars, ", ")

	if f.Type.Results != nil && len(f.Type.Results.List) > 0 {
		m.HasResults = true
		for i, field := range f.Type.Results.List {
			tStr := getExprString(field.Type)
			resTypes = append(resTypes, tStr)
			vName := fmt.Sprintf("res%d", i)
			if tStr == "error" {
				vName, m.HasErr = "err", true
			}
			rvars = append(rvars, vName)
		}
		m.Results = "(" + strings.Join(resTypes, ", ") + ")"
		m.RetVars = strings.Join(rvars, ", ")
		if m.HasErr && len(rvars) > 1 {
			m.HasResultsBeforeErr = true
			m.RetValuesBeforeErr = strings.Join(rvars[:len(rvars)-1], ", ")
		}
	}
	return m
}

func getExprString(expr ast.Expr) string {
	var buf bytes.Buffer
	format.Node(&buf, token.NewFileSet(), expr)
	return buf.String()
}

func importsUsedByMethods(methods []Method, all map[string]string) map[string]string {
	var sig strings.Builder
	for _, m := range methods {
		sig.WriteString(m.Args)
		sig.WriteString(" ")
		sig.WriteString(m.Results)
	}
	s := sig.String()

	used := make(map[string]string)
	for path, line := range all {
		alias := importAlias(line, path)
		if alias != "" && strings.Contains(s, alias+".") {
			used[path] = line
		}
	}
	return used
}

func importAlias(line, path string) string {
	line = strings.TrimSpace(line)
	if strings.Contains(line, " ") {
		return strings.Fields(line)[0]
	}
	path = strings.Trim(path, `"`)
	if i := strings.LastIndex(path, "/"); i >= 0 {
		return path[i+1:]
	}
	return path
}
