// Code generated by obsgen. DO NOT EDIT.
package testdata

import (
	"context"
	"errors"
	"fmt"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

func (r *Repo) Observe() any {
	return newObserveRepo(r)
}

type observeRepo struct {
	*Repo
	label string
}

func newObserveRepo(base *Repo) *observeRepo {
	o := &observeRepo{Repo: base}
	if l, ok := any(base).(interface{ Label() string }); ok {
		o.label = l.Label()
	}
	return o
}

func (o *observeRepo) Label() string {

	return o.Repo.Label()

}

func (o *observeRepo) Save(ctx context.Context, data string) error {

	ctx, span := otel.Tracer("obs").Start(ctx, o.label+"."+"Save")
	defer span.End()

	err := o.Repo.Save(ctx, data)
	if err != nil {

		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())

		return fmt.Errorf("[%s] Save: %w", o.label, err)
	}
	return err

}
